### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by Xiaolong-han** [AI4Bharat/OpenHands#24]
Hello,  thank you for providing such a great framework, but there was an error when I import the module. Could you please offer me a help?
code:

```
import omegaconf
from openhands.apis.classification_model import ClassificationModel
from openhands.core.exp_utils import get_trainer

cfg = omegaconf.OmegaConf.load("1.yaml")
trainer = get_trainer(cfg)

model = ClassificationModel(cfg=cfg, trainer=trainer)
model.init_from_checkpoint_if_available()
model.fit()
```

ERROR:
Traceback (most recent call last):
  File "/home/hxz/project/pose_SLR/main.py", line 3, in <module>
    from openhands.apis.classification_model import ClassificationModel
ModuleNotFoundError: No module named 'openhands.apis'

**Comment by GokulNC** [comment]
Apologies for the inconvenience, and thanks for reporting. It's fixed now.
Please do `pip install --upgrade OpenHands` and try the same now.

**Comment by Xiaolong-han** [comment]
Thanks for your kind help! However, after using`pip install --upgrade OpenHands` , there is a new error

Traceback (most recent call last):
  File "/home/hxz/project/pose_SLR/main.py", line 9, in <module>
    model = ClassificationModel(cfg=cfg, trainer=trainer)
  File "/home/hxz/anaconda3/envs/pose_SLR/lib/python3.7/site-packages/openhands/apis/classification_model.py", line 19, in __init__
    super().__init__(cfg, stage="fit")
  File "/home/hxz/anaconda3/envs/pose_SLR/lib/python3.7/site-packages/openhands/apis/inference.py", line 23, in __init__
    self.model = self.create_model(cfg.model)
  File "/home/hxz/anaconda3/envs/pose_SLR/lib/python3.7/site-packages/openhands/apis/inference.py", line 31, in create_model
    return get_model(cfg, self.datamodule.in_channels, self.datamodule.num_class)
  File "/home/hxz/anaconda3/envs/pose_SLR/lib/python3.7/site-packages/openhands/models/loader.py", line 101, in get_model
    encoder = load_encoder(config.encoder, in_channels)
  File "/home/hxz/anaconda3/envs/pose_SLR/lib/python3.7/site-packages/openhands/models/loader.py", line 17, in load_encoder
    from .encoder.graph.pose_flattener import PoseFlattener
  File "/home/hxz/anaconda3/envs/pose_SLR/lib/python3.7/site-packages/openhands/models/encoder/__init__.py", line 1, in <module>
    from .graph.pose_flattener import PoseFlattener
ModuleNotFoundError: No module named 'openhands.models.encoder.graph'

**Comment by GokulNC** [comment]
Oops. Can you please repeat the same and try again now?

**Comment by Xiaolong-han** [comment]
Wow, thanks a lot. It works!
